// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4sZXVeh3griatOSJ1Yy5ksI24HTreK_E',
    appId: '1:553955093304:web:2875b2c320c19a7736afcd',
    messagingSenderId: '553955093304',
    projectId: 'kizzle-1ac8a',
    authDomain: 'kizzle-1ac8a.firebaseapp.com',
    storageBucket: 'kizzle-1ac8a.firebasestorage.app',
    measurementId: 'G-S9NKVR22DZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_4Jh-_9jE8WQQfQWDfDq0VHHG2Q-sFR4',
    appId: '1:553955093304:android:ffb66750916aa65036afcd',
    messagingSenderId: '553955093304',
    projectId: 'kizzle-1ac8a',
    storageBucket: 'kizzle-1ac8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ-msbqNYMLUwI6nW2cKPNP3jJtWs2A5g',
    appId: '1:553955093304:ios:ea210599f99560be36afcd',
    messagingSenderId: '553955093304',
    projectId: 'kizzle-1ac8a',
    storageBucket: 'kizzle-1ac8a.firebasestorage.app',
    iosBundleId: 'com.example.puzzleBalita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ-msbqNYMLUwI6nW2cKPNP3jJtWs2A5g',
    appId: '1:553955093304:ios:ea210599f99560be36afcd',
    messagingSenderId: '553955093304',
    projectId: 'kizzle-1ac8a',
    storageBucket: 'kizzle-1ac8a.firebasestorage.app',
    iosBundleId: 'com.example.puzzleBalita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4sZXVeh3griatOSJ1Yy5ksI24HTreK_E',
    appId: '1:553955093304:web:6f0f7064d65a9daf36afcd',
    messagingSenderId: '553955093304',
    projectId: 'kizzle-1ac8a',
    authDomain: 'kizzle-1ac8a.firebaseapp.com',
    storageBucket: 'kizzle-1ac8a.firebasestorage.app',
    measurementId: 'G-VT9YV0J4HH',
  );
}
